"""Chunked bottom-up append driver — resumable scale builds that bank progress.

Splits a frozen corpus into N-trial chunks and builds them incrementally:
chunk 1 establishes the base snapshot (a normal --corpus build); every later
chunk is appended via ``--base-snapshot + --add-corpus`` on top of the last good
snapshot. Annotations (the paid LLM extractions/classifications) are optionally
committed after each successful chunk, so a failure mid-way (credit wall, API
outage, a scale-only bug) loses ONLY the in-flight chunk — every prior chunk is
a banked, attributed, committed graph you can ship or inspect.

Why bother (vs one monolithic build):
  * Extraction is the expensive, per-trial, irreversible spend. A monolithic
    build pays for ALL trials' extraction before you can see if the output is
    sane; chunk 1 validates quality for ~chunk_size trials first.
  * The merge's geometric tiers are O(n^2) per node type on a FRESH build but
    O(new x total) on APPEND (the ``node_merge._pair_indices`` seam). Chunked
    appends pay the cheaper append cost and keep each step's wall-clock bounded.
  * Bounded blast radius + resumability — the pattern the 200K north star needs.

Resume after a failure: re-run with ``--start-chunk K`` (the base snapshot from
chunk K-1 persists on disk; chunks are deterministic slices of the corpus).

Usage:
    python -m scripts.chunked_append_build --corpus multi_500 --area multi_500 \
        --chunk-size 75 --include-terminated --concurrency 8 --commit
    # resume from chunk 4 after fixing a credit wall:
    python -m scripts.chunked_append_build --corpus multi_500 --area multi_500 \
        --chunk-size 75 --include-terminated --concurrency 8 --commit --start-chunk 4
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

CORPORA = Path("data/corpora")
EXPORTS = Path("data/exports")


def _load_corpus(name: str) -> list[str]:
    path = CORPORA / f"{name}.txt"
    if not path.exists():
        sys.exit(f"corpus not found: {path}")
    return [
        ln.strip() for ln in path.read_text().splitlines()
        if ln.strip() and not ln.lstrip().startswith("#")
    ]


def _chunks(items: list[str], size: int) -> list[list[str]]:
    return [items[i:i + size] for i in range(0, len(items), size)]


def _write_chunk_file(area: str, idx: int, ncts: list[str]) -> Path:
    path = CORPORA / f"{area}__chunk{idx:03d}.txt"
    header = f"# {area} chunk {idx} — {len(ncts)} NCTs (auto-generated by chunked_append_build)\n"
    path.write_text(header + "\n".join(ncts) + "\n")
    return path


def _run(cmd: list[str], log_path: Path) -> int:
    """Run a build subprocess, teeing output to a per-chunk log + stdout."""
    print(f"\n$ {' '.join(cmd)}\n  (log: {log_path})", flush=True)
    with log_path.open("w") as log:
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        assert proc.stdout is not None
        for line in proc.stdout:
            log.write(line)
            # surface phase rules + the credit-wall signal live
            if any(k in line for k in ("Step ", "Phase 2", "backbone complete",
                                       "chain coverage", "credit balance",
                                       "Aborting", "classify success", "pruned ")):
                print("  " + line.rstrip(), flush=True)
        proc.wait()
        return proc.returncode


def _git_commit_annotations(chunk_idx: int, n: int) -> None:
    subprocess.run(["git", "add", "data/annotations/", "data/corpora/"], check=False)
    msg = (f"data: chunk {chunk_idx} annotations ({n} trials) — chunked append\n\n"
           "Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>")
    r = subprocess.run(["git", "commit", "-q", "-m", msg], capture_output=True, text=True)
    print(f"  git commit: {'ok' if r.returncode == 0 else r.stdout + r.stderr}", flush=True)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", required=True, help="frozen corpus name under data/corpora/")
    ap.add_argument("--area", required=True, help="output prefix for snapshots")
    ap.add_argument("--chunk-size", type=int, default=75)
    ap.add_argument("--concurrency", type=int, default=8)
    ap.add_argument("--include-terminated", action="store_true")
    ap.add_argument("--keep-annotations", action="store_true", default=True)
    ap.add_argument("--commit", action="store_true", help="git-commit annotations after each chunk")
    ap.add_argument("--start-chunk", type=int, default=1, help="1-based; resume after a failure")
    ap.add_argument("--max-trials", type=int, default=None, help="cap total trials (testing)")
    a = ap.parse_args()

    ncts = _load_corpus(a.corpus)
    if a.max_trials:
        ncts = ncts[:a.max_trials]
    chunks = _chunks(ncts, a.chunk_size)
    snapshot = EXPORTS / f"{a.area}_annotated.json"
    print(f"{len(ncts)} trials → {len(chunks)} chunks of ≤{a.chunk_size} "
          f"(starting at chunk {a.start_chunk})")

    common = ["--include-terminated"] if a.include_terminated else []
    common += ["--concurrency", str(a.concurrency)]
    if a.keep_annotations:
        common += ["--keep-annotations"]

    for idx, chunk in enumerate(chunks, start=1):
        if idx < a.start_chunk:
            continue
        cfile = _write_chunk_file(a.area, idx, chunk)
        log_path = Path(f"/tmp/{a.area}_chunk{idx:03d}.log")
        if idx == 1:
            cmd = [sys.executable, "-m", "scripts.build_graph",
                   "--corpus", cfile.stem, "--area", a.area, *common]
        else:
            if not snapshot.exists():
                sys.exit(f"chunk {idx}: base snapshot missing ({snapshot}); "
                         f"re-run from an earlier --start-chunk")
            cmd = [sys.executable, "-m", "scripts.build_graph",
                   "--base-snapshot", str(snapshot),
                   "--add-corpus", str(cfile), "--area", a.area, *common]

        print(f"\n=== chunk {idx}/{len(chunks)} ({len(chunk)} trials) ===", flush=True)
        rc = _run(cmd, log_path)
        if rc != 0:
            print(f"\n✗ chunk {idx} FAILED (exit {rc}). Banked through chunk {idx-1}: "
                  f"{snapshot if snapshot.exists() else '(no base yet)'}\n"
                  f"  Inspect {log_path}; fix (e.g. add credits) and resume:\n"
                  f"  python -m scripts.chunked_append_build --corpus {a.corpus} "
                  f"--area {a.area} --chunk-size {a.chunk_size} "
                  f"{'--include-terminated ' if a.include_terminated else ''}"
                  f"--concurrency {a.concurrency} "
                  f"{'--commit ' if a.commit else ''}--start-chunk {idx}", flush=True)
            sys.exit(rc)
        print(f"✓ chunk {idx} done.", flush=True)
        if a.commit:
            _git_commit_annotations(idx, len(chunk))

    print(f"\n✓ all {len(chunks)} chunks built → {snapshot}")


if __name__ == "__main__":
    main()
